# Generated by Django 6.1.1 on 2026-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="genre",
            field=models.CharField(default="all", max_length=20),
        ),
        migrations.AddField(
            model_name="room",
            name="provider",
            field=models.CharField(default="all", max_length=20),
        ),
    ]
